name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run checks for DataVault with Redis version ${{ matrix.redis-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5, 6]
    env:
      REDIS_URL: redis://@127.0.0.1/
      ENCRYPTED_DATA_VAULT_KEY: 000102030405060708090a0b0c0d0e0f
      ENCRYPTED_DATA_VAULT_IV: f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CRITERION_TOKEN: ${{ secrets.CRITERION_TOKEN }}

    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Checkout Data Vault
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmarks
        run: |
          # run benchmarks and save baseline to "criterion.dev.temp"
          cargo bench -- --verbose --noplot --save-baseline criterion.dev.temp

          # set the path to the file to upload to criterion.dev
          echo "::set-env name=CRITERION_FILE_PATH::$(find $(find . -type d -name criterion.dev.temp) -name raw.csv)"
      - name: Upload benchmarks
        run: |
          # upload the file
          curl -F 'raw.csv=@${{ env.CRITERION_FILE_PATH }}' \
          'https://api.criterion.dev/v1/${{ github.repository }}/measurements?token=${{ secrets.CRITERION_TOKEN }}&commit=${{ github.sha }}'
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run tarpaulin
        run: cargo tarpaulin --out Xml
      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
