
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [4, 5, 6]
    env:
      REDIS_URL: redis://@127.0.0.1/
      ENCRYPTED_DATA_VAULT_KEY: 000102030405060708090a0b0c0d0e0f
      ENCRYPTED_DATA_VAULT_IV: f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff

    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Checkout Data Vault
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: Run benchmarks
        run: cargo bench --verbose
      - name: Install grcov
        run: cargo install grcov
      - name: Run grcov
        run: grcov ./target/debug -t coveralls -s . --token ${{ secrets.CODECOV_TOKEN }} > codecov.json
      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: codecov.json
          fail_ci_if_error: true
